### ISSUE TITLE
Can't access ShEx functionalities 

### ISSUE THREAD

**Issue by ulitol97** [weso/rdfshape-client#20]
While implementing some enhancements to the client I realized I couldn't access the pages related to ShEx operations:

- http://rdfshape.weso.es/shExValidate
- http://rdfshape.weso.es/shExValidateEndpoint
- http://rdfshape.weso.es/shExInfo
- http://rdfshape.weso.es/shExVisualize
- http://rdfshape.weso.es/shExConvert
- http://rdfshape.weso.es/shEx2Shacl

All I get is a blank page and the following error in the console:  
`TypeError: Cannot read property 'line' of undefined`  
    `at yashe.bundled.min.js:29480`
    `at s (yashe.bundled.min.js:5605)`
    `at t (yashe.bundled.min.js:5620)`
    `at x.foldCode (yashe.bundled.min.js:5667)`
    `at x.e.collapsePrefixes (yashe.bundled.min.js:28673)`
    `at w (yashe.bundled.min.js:28850)`
    `at Function.v.fromTextArea (yashe.bundled.min.js:28924)`
    `at ShExForm.js:16`
    `at ml (react-dom.production.min.js:4706)`
    `at Fs (react-dom.production.min.js:6471)`
`vl @ react-dom.production.min.js:4636`
`react-dom.production.min.js:2835`

Does it happen to you as well? @labra @mistermboy 
Cant it be related to #19 or am I missing something?

**Comment by labra** [comment]
You are right!, it's strange, because when I use `npm start` locally it works.

It seems to fail only in the deployed version.

@mistermboy, any hint ?

**Comment by labra** [comment]
Until now, it was strange because it worked in my computer, but now I noticed it also fails and that the  [Travis tests fail also](https://travis-ci.org/github/weso/rdfshape-client/builds/670045646)...so we could try to focus on solving the tests.

Could it be a problem with the library versions? 

Could you add some similar test to wikishape to see if it also fails?

Another possibility would be to create a simple skeleton of a project invoking YaShE to see if it pases the tests.

Finally, I think we should refactor both Wikishape and RDFShape to put the common code in another library which could be published in npm and reused from there.

**Comment by ulitol97** [comment]
Indeed, the tests I created to test the rendering of the page do not pass either in local or in Travis.

I'll create similar tests for WikiShape while searching for clues on the error. For now, I created an issue similar to this one for WikiShape where I list the pages affected by this problem: https://github.com/weso/wikishape/issues/9.

I'll update the issues with any news. Once the problem is solved we can start refactoring.
